### ISSUE TITLE
Maybe a new project 

### ISSUE THREAD

**Issue by yuxino** [yuxino/meteorite#32]
Almost a month ago, I wanted to develop ruka 2.0. But today i think maybe create a new project is better than develop ruka 2.0 .. ruka is a serverless blog system , using ajax to fetch github issues as articles to build my own blog site . But ruka has some disadvantage: 

- Not friendly to seo, Because we are dynamically rendering the page using js . 
- Ruka is not safe, We exposed the private key of github issues in the repository. Other people can also use this key to fetch u blog issues to  disguise your blog site. This is not a solution except for the existence of the key on the server side. But even if you don't expose the key, others have a way to copy your article, for example, through a crawler download all u issues. This is actually not a big problem with ruka.

Despite this ruka have some good feature:

- You don't need a server , u can using github page / surge / now to deploy u own site. You don't need to worry about whether the server expires, whether the server is down, etc.
- Once the issues are updated, the articles will be updated automatically. No need to redeploy like those of hexo.
- If you have learned react, you can easily change the code of ruka. Because ruka is built on typescript. The source code itself is the document
- Online editing You can edit your issues on any device. 

The problem of SEO is actually quite serious for a blog. Although ruka has many advantages, it can't cover up this shortcoming. he first screen loading is also the weakness of ruka . 

Yes . I may need to make some compromises to using server to create a new `ruka` or generate a blog by statically rendering a similar hexo. But no matter which means, I don't want to change the original intention of ruka, I will open a new project to complete this.

In the future, I might want to update my blog with some more cool way, change the habit of writing articles for a long time. I am writing my own markdown editor. I may unlocked it out from the private repository.

Some awesome project can inspire me

- [medium-to-own-blog](https://github.com/mathieudutour/medium-to-own-blog)

**Comment by LonelyLiaR** [comment]
with [NextJS](https://nextjs.org/) ?

**Comment by Nbsaw** [comment]
@LonelyLiaR No, just a cli to generate site. using server side render but not nextJs.

**Comment by LonelyLiaR** [comment]
@Nbsaw sounds awesome. 弄好艾特我康康. 🙇‍♂️

**Comment by Nbsaw** [comment]
@LonelyLiaR 给你点思路 Webpack有个叫`Manifest`的东西。可以把`Manifest`输出成一个文件。`Manifest`有编译的上下文信息。比如知道`entry`,知道`publicPath`,知道有什么`assest`等等。然后`Vue`或者`React`提供的工具会读取这个`Manifest`。服务端就知道哪些文件是有用的，你要干什么。`React Router`匹配对应的路径的组件，再在服务端渲染出来就行了。然后客户端把它变成SPA。

首屏服务端渲染 -> SPA

**Comment by LonelyLiaR** [comment]
@Nbsaw ok, 我看一下.
